version: '3'
services:
  db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: MongoDB2019!
    ports:
      - 27017:27017
    volumes:
      - db_data:/data/db

  kong-database:
    image: postgres:10.6
    restart: always
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong

  kong-migration:
    image: kong:latest
    command: "kong migrations bootstrap"
    restart: on-failure
    environment:
      - KONG_PG_HOST=kong-database
    depends_on:
      - kong-database

  kong:
    image: kong:latest
    restart: always
    environment:
      - KONG_PG_HOST=kong-database
      - KONG_PROXY_LISTEN=0.0.0.0:8000
      - KONG_PROXY_LISTEN_SSL=0.0.0.0:8443
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
    depends_on:
      - kong-migration
      - kong-database
    ports:
      - 8001:8001
      - 80:8000

  konga:
    image: pantsel/konga:latest
    restart: always
    environment:
      - DB_ADAPTER=postgres
      - DB_DATABASE=konga_database
      - DB_HOST=kong-database
      - DB_USER=kong
    depends_on:
      - kong
      - kong-database
    ports:
      - 1337:1337

volumes:
  db_data:
